/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PersonalCodexAssistantPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/codex/CodexAuth.ts
var import_child_process = require("child_process");

// src/codex/CodexCommand.ts
var import_fs = require("fs");
var import_path = require("path");
function buildCodexCommand(command, args) {
  const resolved = resolveCommandPath(command);
  if (process.platform === "win32" && /\.cmd$/i.test(resolved)) {
    return {
      command: "cmd.exe",
      args: ["/d", "/c", "call", resolved, ...args],
      windowsHide: true
    };
  }
  return {
    command: resolved,
    args,
    windowsHide: true
  };
}
function resolveCommandPath(command) {
  if (process.platform !== "win32" || command.includes("\\") || command.includes("/")) {
    return command;
  }
  const appData = process.env.APPDATA;
  const candidates = [
    appData ? (0, import_path.join)(appData, "npm", `${command}.cmd`) : "",
    appData ? (0, import_path.join)(appData, "npm", command) : ""
  ].filter(Boolean);
  for (const candidate of candidates) {
    if ((0, import_fs.existsSync)(candidate)) {
      return candidate;
    }
  }
  return command;
}

// src/codex/CodexHome.ts
var import_fs2 = require("fs");
var import_os = require("os");
var import_path2 = require("path");
function getDefaultCodexHome() {
  return (0, import_path2.join)((0, import_os.homedir)(), ".codex");
}
function getAssistantCodexHome() {
  return (0, import_path2.join)((0, import_os.homedir)(), ".codex-obsidian-assistant");
}
function syncAssistantCodexHome() {
  const sourceHome = getDefaultCodexHome();
  const targetHome = getAssistantCodexHome();
  (0, import_fs2.mkdirSync)(targetHome, { recursive: true });
  const sourceAuth = (0, import_path2.join)(sourceHome, "auth.json");
  const targetAuth = (0, import_path2.join)(targetHome, "auth.json");
  if ((0, import_fs2.existsSync)(sourceAuth)) {
    (0, import_fs2.copyFileSync)(sourceAuth, targetAuth);
  }
  const targetConfig = (0, import_path2.join)(targetHome, "config.toml");
  if (!(0, import_fs2.existsSync)(targetConfig)) {
    (0, import_fs2.writeFileSync)(targetConfig, 'approval_policy = "never"\n', "utf8");
  }
  return targetHome;
}
function clearAssistantCodexHomeAuth() {
  const targetAuth = (0, import_path2.join)(getAssistantCodexHome(), "auth.json");
  if ((0, import_fs2.existsSync)(targetAuth)) {
    (0, import_fs2.rmSync)(targetAuth, { force: true });
  }
}

// src/codex/CodexAuth.ts
var CodexAuth = class {
  constructor(command) {
    this.command = command;
  }
  checkStatus() {
    return new Promise((resolve) => {
      const resolved = buildCodexCommand(this.command, ["login", "status"]);
      const child = (0, import_child_process.spawn)(resolved.command, resolved.args, {
        shell: false,
        windowsHide: resolved.windowsHide
      });
      let output = "";
      child.stdout.on("data", (chunk) => {
        output += chunk.toString("utf8");
      });
      child.stderr.on("data", (chunk) => {
        output += chunk.toString("utf8");
      });
      child.on("error", (error) => {
        resolve({
          available: false,
          signedIn: false,
          output: error.message
        });
      });
      child.on("exit", (code) => {
        resolve({
          available: true,
          signedIn: code === 0 && !/not logged in|not signed in|no active/i.test(output),
          output: output.trim()
        });
      });
    });
  }
  login(onLog) {
    return new Promise((resolve) => {
      const resolved = buildCodexCommand(this.command, ["login"]);
      const child = (0, import_child_process.spawn)(resolved.command, resolved.args, {
        shell: false,
        windowsHide: resolved.windowsHide
      });
      child.stdout.on("data", (chunk) => {
        this.handleLoginOutput(chunk.toString("utf8"), onLog);
      });
      child.stderr.on("data", (chunk) => {
        this.handleLoginOutput(chunk.toString("utf8"), onLog);
      });
      child.on("error", (error) => {
        onLog(error.message);
        resolve(null);
      });
      child.on("exit", (code) => {
        clearAssistantCodexHomeAuth();
        resolve(code);
      });
    });
  }
  logout(onLog) {
    return new Promise((resolve) => {
      const resolved = buildCodexCommand(this.command, ["logout"]);
      const child = (0, import_child_process.spawn)(resolved.command, resolved.args, {
        shell: false,
        windowsHide: resolved.windowsHide
      });
      child.stdout.on("data", (chunk) => {
        const message = chunk.toString("utf8").trim();
        if (message) {
          onLog(message);
        }
      });
      child.stderr.on("data", (chunk) => {
        const message = chunk.toString("utf8").trim();
        if (message) {
          onLog(message);
        }
      });
      child.on("error", (error) => {
        onLog(error.message);
        resolve(null);
      });
      child.on("exit", (code) => {
        resolve(code);
      });
    });
  }
  handleLoginOutput(output, onLog) {
    const trimmed = output.trim();
    if (trimmed) {
      onLog(trimmed);
    }
    const urls = output.match(/https?:\/\/\S+/gu) ?? [];
    for (const url of urls) {
      this.openExternalUrl(url.replace(/[.)\]]+$/u, ""));
    }
  }
  openExternalUrl(url) {
    try {
      const electron = require("electron");
      electron.shell?.openExternal(url);
    } catch {
    }
  }
};

// src/codex/CodexProcess.ts
var import_child_process2 = require("child_process");
var CodexProcess = class {
  constructor(command, args, onEvent) {
    this.command = command;
    this.args = args;
    this.onEvent = onEvent;
  }
  child = null;
  buffer = "";
  get isRunning() {
    return this.child !== null;
  }
  start() {
    if (this.child) {
      return;
    }
    try {
      const codexHome = syncAssistantCodexHome();
      const resolved = buildCodexCommand(this.command, this.args);
      this.child = (0, import_child_process2.spawn)(resolved.command, resolved.args, {
        env: {
          ...process.env,
          CODEX_HOME: codexHome
        },
        stdio: ["pipe", "pipe", "pipe"],
        shell: false,
        windowsHide: resolved.windowsHide
      });
    } catch (error) {
      this.child = null;
      this.onEvent({ type: "error", payload: error instanceof Error ? error : new Error(String(error)) });
      return;
    }
    this.child.stdout.on("data", (chunk) => this.handleStdout(chunk));
    this.child.stderr.on("data", (chunk) => {
      this.onEvent({ type: "stderr", payload: chunk.toString("utf8") });
    });
    this.child.on("error", (error) => {
      this.onEvent({ type: "error", payload: error });
    });
    this.child.on("exit", (code) => {
      this.child = null;
      this.buffer = "";
      this.onEvent({ type: "exit", payload: code });
    });
  }
  stop() {
    this.child?.kill();
    this.child = null;
    this.buffer = "";
  }
  send(message) {
    if (!this.child) {
      throw new Error("Codex app-server\uAC00 \uC2E4\uD589\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.");
    }
    this.child.stdin.write(`${JSON.stringify(message)}
`);
  }
  handleStdout(chunk) {
    this.buffer += chunk.toString("utf8");
    const lines = this.buffer.split("\n");
    this.buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        continue;
      }
      try {
        this.onEvent({ type: "message", payload: JSON.parse(trimmed) });
      } catch {
        this.onEvent({ type: "stderr", payload: `JSON \uD30C\uC2F1 \uC2E4\uD328: ${trimmed}` });
      }
    }
  }
};

// src/codex/CodexClient.ts
var CodexClient = class {
  process;
  nextId = 1;
  handlers = /* @__PURE__ */ new Set();
  initialized = false;
  threadId = null;
  pendingPrompt = null;
  pendingThreadStartId = null;
  constructor(settings) {
    this.process = new CodexProcess(
      settings.codexCommand,
      settings.codexArgs,
      (event) => this.emit(event)
    );
  }
  get isRunning() {
    return this.process.isRunning;
  }
  onEvent(handler) {
    this.handlers.add(handler);
    return () => this.handlers.delete(handler);
  }
  start() {
    this.process.start();
    this.initialize();
  }
  stop() {
    this.process.stop();
    this.initialized = false;
    this.threadId = null;
    this.pendingPrompt = null;
    this.pendingThreadStartId = null;
  }
  send(method, params) {
    const request = {
      id: this.nextId++,
      method,
      params
    };
    this.process.send(request);
    return request.id;
  }
  notify(method, params) {
    const notification = { method, params };
    this.process.send(notification);
  }
  sendPrompt(prompt) {
    if (!this.isRunning) {
      this.start();
    }
    if (this.threadId) {
      this.startTurn(prompt);
      return;
    }
    this.pendingPrompt = prompt;
    this.pendingThreadStartId = this.send("thread/start", {});
  }
  emit(event) {
    if (event.type === "message") {
      this.handleProtocolMessage(event.payload);
    }
    for (const handler of this.handlers) {
      handler(event);
    }
  }
  initialize() {
    if (this.initialized) {
      return;
    }
    this.send("initialize", {
      clientInfo: {
        name: "personal_codex_assistant",
        title: "Personal Codex Assistant",
        version: "0.1.0"
      }
    });
    this.notify("initialized", {});
    this.initialized = true;
  }
  handleProtocolMessage(payload) {
    if (!payload || typeof payload !== "object" || payload instanceof Error) {
      return;
    }
    const message = payload;
    if (message.id !== this.pendingThreadStartId || !message.result || typeof message.result !== "object") {
      return;
    }
    const result = message.result;
    const thread = result.thread;
    if (!thread || typeof thread !== "object") {
      return;
    }
    const id = thread.id;
    if (typeof id !== "string") {
      return;
    }
    this.threadId = id;
    this.pendingThreadStartId = null;
    const prompt = this.pendingPrompt;
    this.pendingPrompt = null;
    if (prompt) {
      this.startTurn(prompt);
    }
  }
  startTurn(prompt) {
    if (!this.threadId) {
      throw new Error("Codex thread\uAC00 \uC544\uC9C1 \uC900\uBE44\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.");
    }
    this.send("turn/start", {
      threadId: this.threadId,
      input: [
        {
          type: "text",
          text: prompt
        }
      ]
    });
  }
};

// src/context/VaultContext.ts
var import_obsidian = require("obsidian");
var VaultContext = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async getActiveNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("\uC5F4\uB824 \uC788\uB294 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return null;
    }
    const content = await this.app.vault.read(file);
    const selection = this.getSelection();
    return { file, content, selection };
  }
  getSelection() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    return view?.editor.getSelection() ?? "";
  }
  async ensureAssistantFiles() {
    await this.ensureFolder(this.settings.assistantFolder);
    await this.ensureFolder(this.settings.dailyReviewFolder);
    const files = [
      [
        "Profile.md",
        [
          "# Profile",
          "",
          "- \uC774\uB984:",
          "- \uD604\uC7AC \uC9D1\uC911\uD558\uB294 \uC77C:",
          "- \uC911\uC694\uD558\uAC8C \uC5EC\uAE30\uB294 \uAC83:",
          ""
        ].join("\n")
      ],
      [
        "Preferences.md",
        [
          "# Preferences",
          "",
          "## Assistant Tone",
          "- \uD55C\uAD6D\uC5B4\uB85C \uB9D0\uD55C\uB2E4.",
          "- \uB108\uBB34 \uB531\uB531\uD55C \uBCF4\uACE0\uC11C \uB9D0\uD22C\uBCF4\uB2E4, \uB0B4 \uC0C1\uD669\uC744 \uC774\uD574\uD55C \uAC1C\uC778 \uBE44\uC11C\uCC98\uB7FC \uB9D0\uD55C\uB2E4.",
          "- \uBB34\uC870\uAC74 \uC704\uB85C\uD558\uC9C0 \uB9D0\uACE0, \uD574\uC57C \uD560 \uC77C\uC744 \uD604\uC2E4\uC801\uC73C\uB85C \uC815\uB9AC\uD55C\uB2E4.",
          "- \uC7A5\uD669\uD55C \uC124\uBA85\uBCF4\uB2E4 \uBC14\uB85C \uC2E4\uD589 \uAC00\uB2A5\uD55C \uB2E4\uC74C \uD589\uB3D9\uC744 \uC6B0\uC120\uD55C\uB2E4.",
          "- \uB0B4\uAC00 \uC4F4 \uD45C\uD604\uACFC \uAD00\uC2EC\uC0AC\uB97C \uCD5C\uB300\uD55C \uBC18\uC601\uD55C\uB2E4.",
          "",
          "## Feedback Style",
          "- \uC6B0\uC120\uC21C\uC704\uAC00 \uD750\uB824\uC9C0\uBA74 \uBA85\uD655\uD558\uAC8C \uC9DA\uC5B4\uC900\uB2E4.",
          "- \uACF5\uBD80, \uAC1C\uBC1C, \uC77C\uC815, \uBBF8\uB8EC \uC77C\uC744 \uAD6C\uBD84\uD574\uC11C \uC815\uB9AC\uD55C\uB2E4.",
          "- \uD560 \uC77C\uC744 \uB108\uBB34 \uB9CE\uC774 \uB9CC\uB4E4\uC9C0 \uB9D0\uACE0 \uC624\uB298 \uC2E4\uC81C\uB85C \uD560 \uC218 \uC788\uB294 \uC591\uC73C\uB85C \uC904\uC778\uB2E4.",
          ""
        ].join("\n")
      ],
      ["Goals.md", "# Goals\n\n"],
      ["Projects.md", "# Projects\n\n"],
      ["Routines.md", "# Routines\n\n"]
    ];
    for (const [name, content] of files) {
      const path = `${this.settings.assistantFolder}/${name}`;
      if (!this.app.vault.getAbstractFileByPath(path)) {
        await this.app.vault.create(path, content);
      }
    }
  }
  async saveDailyReview(markdown) {
    await this.ensureFolder(this.settings.dailyReviewFolder);
    const date = window.moment().format("YYYY-MM-DD");
    const path = `${this.settings.dailyReviewFolder}/${date}.md`;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existing, markdown);
    } else {
      await this.app.vault.create(path, markdown);
    }
    return path;
  }
  buildPrompt(userInput, mode) {
    const base = [
      "\uB108\uB294 Obsidian \uC548\uC5D0\uC11C \uB3D9\uC791\uD558\uB294 \uAC1C\uC778 \uBE44\uC11C\uB2E4.",
      "\uC0AC\uC6A9\uC790\uC758 \uB178\uD2B8, \uBAA9\uD45C, \uC120\uD638\uB97C \uBC14\uD0D5\uC73C\uB85C \uB2F5\uD55C\uB2E4.",
      "\uB9D0\uD22C\uB294 \uC778\uAC04\uC801\uC778 \uAC1C\uC778 \uBE44\uC11C\uC5D0 \uAC00\uAE5D\uAC8C \uD558\uB418, \uACFC\uC7A5\uB41C \uAC10\uC815 \uD45C\uD604\uC774\uB098 \uC758\uBBF8 \uC5C6\uB294 \uCE6D\uCC2C\uC740 \uD53C\uD55C\uB2E4.",
      "\uC0AC\uC6A9\uC790\uAC00 \uC4F4 \uD45C\uD604, \uBC18\uBCF5\uB418\uB294 \uAD00\uC2EC\uC0AC, \uBBF8\uB904\uC9C4 \uC77C, \uD604\uC7AC \uC5D0\uB108\uC9C0\uB97C \uCD94\uB860\uD574\uC11C \uBC18\uC601\uD55C\uB2E4.",
      "\uB2F5\uBCC0\uC740 \uAD6C\uCCB4\uC801\uC774\uACE0 \uBC14\uB85C \uC2E4\uD589 \uAC00\uB2A5\uD574\uC57C \uD55C\uB2E4.",
      "\uD30C\uC77C\uC744 \uC9C1\uC811 \uC218\uC815\uD558\uC9C0 \uB9D0\uACE0 \uC81C\uC548\uB9CC \uD55C\uB2E4."
    ];
    if (mode === "daily-review") {
      return [
        ...base,
        "",
        "\uD604\uC7AC \uB178\uD2B8\uC5D0 \uC801\uD78C \uC77C\uAE30, TODO, \uACF5\uBD80 \uAE30\uB85D\uC744 \uC77D\uACE0 \uB2E4\uC74C \uD615\uC2DD\uC73C\uB85C \uC815\uB9AC\uD574\uB77C.",
        "\uB2E8\uC21C \uC694\uC57D\uBCF4\uB2E4 \uC0AC\uC6A9\uC790\uAC00 \uC2E4\uC81C\uB85C \uC624\uB298 \uBB34\uC5C7\uC744 \uD558\uBA74 \uC88B\uC744\uC9C0 \uD310\uB2E8\uD574\uB77C.",
        "",
        "## \uC624\uB298 \uC694\uC57D",
        "## \uC9C0\uAE08 \uC2E0\uACBD \uC368\uC57C \uD560 \uAC83",
        "## \uD574\uC57C \uD560 \uC77C",
        "## \uC77C\uC815",
        "## \uC6B0\uC120\uC21C\uC704",
        "## \uB0B4\uC77C\uB85C \uB118\uAE38 \uC77C",
        "",
        "\uC0AC\uC6A9\uC790 \uC694\uCCAD:",
        userInput
      ].join("\n");
    }
    if (mode === "selection") {
      return [
        ...base,
        "",
        "\uC120\uD0DD \uC601\uC5ED\uC744 \uC0AC\uC6A9\uC790\uC758 \uAE30\uC874 \uBB38\uCCB4\uC640 \uC758\uB3C4\uB97C \uC0B4\uB824 \uB2E4\uB4EC\uC5B4\uB77C.",
        "\uC6D0\uBB38\uC744 \uB300\uC2E0 \uC368\uC8FC\uAE30 \uC804\uC5D0, \uC5B4\uB5A4 \uBC29\uD5A5\uC73C\uB85C \uACE0\uCCE4\uB294\uC9C0 \uC9E7\uAC8C \uB9D0\uD574\uB77C.",
        "",
        "\uC0AC\uC6A9\uC790 \uC694\uCCAD:",
        userInput
      ].join("\n");
    }
    return [
      ...base,
      "",
      "\uC0AC\uC6A9\uC790 \uC694\uCCAD:",
      userInput
    ].join("\n");
  }
  async buildContextualPrompt(userInput, includeSelectionOnly, dailyReview) {
    const active = await this.getActiveNote();
    if (!active) {
      return null;
    }
    const memory = await this.readAssistantMemory();
    const useSelection = includeSelectionOnly && active.selection.trim().length > 0;
    const source = useSelection ? active.selection : active.content;
    const label = useSelection ? "\uC120\uD0DD \uC601\uC5ED" : "\uD604\uC7AC \uB178\uD2B8";
    const instruction = this.buildPrompt(userInput, dailyReview ? "daily-review" : useSelection ? "selection" : "active");
    return [
      instruction,
      "",
      "\uAC1C\uC778 \uBB38\uB9E5:",
      this.formatMemory(memory),
      "",
      `\uCCA8\uBD80 \uBB38\uB9E5: ${label}`,
      `\uD30C\uC77C\uBA85: ${active.file.path}`,
      "",
      "\uC774 \uB178\uD2B8\uC758 \uBB38\uC7A5\uACFC \uB2E8\uC5B4 \uC120\uD0DD\uC744 \uC0AC\uC6A9\uC790\uC758 \uD604\uC7AC \uB9D0\uD22C \uC0D8\uD50C\uB85C \uCC38\uACE0\uD574\uB77C.",
      "",
      "```markdown",
      source,
      "```"
    ].join("\n");
  }
  async readAssistantMemory() {
    return {
      profile: await this.readOptionalFile(`${this.settings.assistantFolder}/Profile.md`),
      preferences: await this.readOptionalFile(`${this.settings.assistantFolder}/Preferences.md`),
      goals: await this.readOptionalFile(`${this.settings.assistantFolder}/Goals.md`),
      projects: await this.readOptionalFile(`${this.settings.assistantFolder}/Projects.md`),
      routines: await this.readOptionalFile(`${this.settings.assistantFolder}/Routines.md`)
    };
  }
  async readOptionalFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) {
      return "";
    }
    return this.truncate(await this.app.vault.read(file), 3e3);
  }
  formatMemory(memory) {
    return [
      "## Profile",
      memory.profile || "(\uBE44\uC5B4 \uC788\uC74C)",
      "",
      "## Preferences",
      memory.preferences || "(\uBE44\uC5B4 \uC788\uC74C)",
      "",
      "## Goals",
      memory.goals || "(\uBE44\uC5B4 \uC788\uC74C)",
      "",
      "## Projects",
      memory.projects || "(\uBE44\uC5B4 \uC788\uC74C)",
      "",
      "## Routines",
      memory.routines || "(\uBE44\uC5B4 \uC788\uC74C)"
    ].join("\n");
  }
  truncate(value, maxLength) {
    if (value.length <= maxLength) {
      return value;
    }
    return `${value.slice(0, maxLength)}

...(\uC77C\uBD80 \uC0DD\uB7B5\uB428)`;
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }
};

// src/security/ApprovalManager.ts
var ApprovalManager = class {
  fileWritesEnabled = false;
  explainReadOnlyMode() {
    return "v0.1\uC740 \uB178\uD2B8\uB97C \uC9C1\uC811 \uC218\uC815\uD558\uC9C0 \uC54A\uACE0 \uC218\uC815 \uC81C\uC548\uB9CC \uD45C\uC2DC\uD569\uB2C8\uB2E4.";
  }
};

// src/settings/AssistantSettings.ts
var DEFAULT_SETTINGS = {
  codexCommand: "codex",
  codexArgs: ["app-server", "--stdio"],
  assistantFolder: "Assistant",
  dailyFolder: "Daily",
  dailyReviewFolder: "Assistant/Daily Review"
};

// src/views/AssistantView.ts
var import_obsidian2 = require("obsidian");
var ASSISTANT_VIEW_TYPE = "personal-codex-assistant-view";
var AssistantView = class extends import_obsidian2.ItemView {
  constructor(leaf, codex, auth, vaultContext, approvals) {
    super(leaf);
    this.codex = codex;
    this.auth = auth;
    this.vaultContext = vaultContext;
    this.approvals = approvals;
  }
  messagesEl;
  inputEl;
  statusEl;
  rootEl;
  lastAssistantText = "";
  getViewType() {
    return ASSISTANT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Codex Assistant";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("personal-codex-assistant");
    this.rootEl = container;
    await this.render();
    this.codex.onEvent((event) => this.handleCodexEvent(event));
  }
  async render() {
    this.rootEl.empty();
    this.rootEl.addClass("personal-codex-assistant");
    const authStatus = await this.auth.checkStatus();
    if (!authStatus.signedIn) {
      this.renderSignedOut(authStatus.output, authStatus.available);
      return;
    }
    this.renderChat();
  }
  renderHeader(subtitle) {
    const header = this.rootEl.createDiv({ cls: "pca-header" });
    const mark = header.createDiv({ cls: "pca-orbit-mark" });
    mark.createDiv({ cls: "pca-orbit-core" });
    const titleWrap = header.createDiv({ cls: "pca-title-wrap" });
    titleWrap.createEl("h2", { text: "Personal Codex Assistant" });
    titleWrap.createEl("p", { text: subtitle });
  }
  renderSignedOut(output, available) {
    this.renderHeader("ChatGPT \uACC4\uC815\uC73C\uB85C Codex\uB97C \uC5F0\uACB0\uD558\uC138\uC694.");
    const messages = this.rootEl.createDiv({ cls: "pca-messages pca-auth-panel" });
    messages.createEl("strong", { cls: "pca-role", text: "\uB85C\uADF8\uC778 \uD544\uC694" });
    messages.createEl("div", {
      text: available ? "\uBE0C\uB77C\uC6B0\uC800\uC5D0\uC11C ChatGPT \uB85C\uADF8\uC778\uC744 \uC644\uB8CC\uD558\uBA74 \uC774\uD6C4\uC5D0\uB294 \uB85C\uCEEC Codex \uC138\uC158\uC744 \uC7AC\uC0AC\uC6A9\uD569\uB2C8\uB2E4." : "Codex CLI\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. Codex CLI \uC124\uCE58 \uB610\uB294 PATH \uC124\uC815\uC774 \uD544\uC694\uD569\uB2C8\uB2E4."
    });
    if (output) {
      messages.createEl("pre", { text: output });
    }
    const toolbar = this.rootEl.createDiv({ cls: "pca-toolbar" });
    const loginButton = toolbar.createEl("button", { text: "ChatGPT\uB85C \uB85C\uADF8\uC778" });
    loginButton.disabled = !available;
    loginButton.onclick = () => this.startLogin(loginButton);
    const refreshButton = toolbar.createEl("button", { text: "\uC0C1\uD0DC \uB2E4\uC2DC \uD655\uC778" });
    refreshButton.onclick = () => this.render();
    this.statusEl = this.rootEl.createEl("div", {
      cls: "pca-status",
      text: available ? "\uB85C\uADF8\uC778 \uB300\uAE30 \uC911" : "Codex CLI \uC5C6\uC74C"
    });
  }
  renderChat() {
    this.renderHeader("\uB178\uD2B8\uC640 \uBAA9\uD45C\uB97C \uC77D\uACE0 \uB2E4\uC74C \uD589\uB3D9\uC744 \uC815\uB9AC\uD569\uB2C8\uB2E4.");
    const toolbar = this.rootEl.createDiv({ cls: "pca-toolbar" });
    this.createToolbarButton(toolbar, "\uB85C\uADF8\uC778 \uC0C1\uD0DC", async () => {
      const status = await this.auth.checkStatus();
      this.addMessage("\uC2DC\uC2A4\uD15C", status.signedIn ? "Codex \uB85C\uADF8\uC778 \uC0C1\uD0DC\uC785\uB2C8\uB2E4." : "Codex \uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4.");
    });
    this.createToolbarButton(toolbar, "\uB2E4\uC2DC \uB85C\uADF8\uC778", () => {
      this.relogin();
    });
    this.createToolbarButton(toolbar, "\uD604\uC7AC \uB178\uD2B8 \uC694\uC57D", () => {
      this.sendWithContext("\uD604\uC7AC \uB178\uD2B8\uB97C \uAC04\uACB0\uD558\uAC8C \uC694\uC57D\uD574\uC918.", false, false);
    });
    this.createToolbarButton(toolbar, "\uC624\uB298 \uC815\uB9AC", () => {
      this.sendWithContext("\uC624\uB298 \uAE30\uB85D\uC744 \uBC14\uD0D5\uC73C\uB85C \uD574\uC57C \uD560 \uC77C, \uC77C\uC815, \uC6B0\uC120\uC21C\uC704\uB97C \uC815\uB9AC\uD574\uC918.", false, true);
    });
    this.createToolbarButton(toolbar, "\uC120\uD0DD \uC601\uC5ED \uB2E4\uB4EC\uAE30", () => {
      this.sendWithContext("\uC120\uD0DD \uC601\uC5ED\uC744 \uB354 \uC790\uC5F0\uC2A4\uB7FD\uACE0 \uBA85\uD655\uD55C \uBB38\uC7A5\uC73C\uB85C \uACE0\uCCD0\uC918. \uC6D0\uBB38\uC744 \uC9C1\uC811 \uC218\uC815\uD558\uC9C0 \uB9D0\uACE0 \uC81C\uC548\uBB38\uB9CC \uBCF4\uC5EC\uC918.", true, false);
    });
    this.createToolbarButton(toolbar, "\uB2F5\uBCC0 \uC800\uC7A5", () => {
      this.saveDailyReview();
    });
    const contextRow = this.rootEl.createDiv({ cls: "pca-context-row" });
    contextRow.createEl("span", {
      cls: "pca-status",
      text: this.approvals.explainReadOnlyMode()
    });
    this.messagesEl = this.rootEl.createDiv({ cls: "pca-messages" });
    this.addMessage("\uC2DC\uC2A4\uD15C", "Codex \uC5F0\uACB0 \uC804\uC785\uB2C8\uB2E4. \uC9C8\uBB38\uC744 \uBCF4\uB0B4\uBA74 app-server \uC2E4\uD589\uC744 \uC2DC\uB3C4\uD569\uB2C8\uB2E4.");
    const compose = this.rootEl.createDiv({ cls: "pca-compose" });
    this.inputEl = compose.createEl("textarea", {
      placeholder: "Codex\uC5D0\uAC8C \uC694\uCCAD\uD558\uC138\uC694. \uD604\uC7AC \uB178\uD2B8\uB97C \uD568\uAED8 \uBCF4\uB0C5\uB2C8\uB2E4."
    });
    const sendButton = compose.createEl("button", { text: "\uC804\uC1A1" });
    sendButton.onclick = () => this.sendWithContext(this.inputEl.value, false, false);
    this.statusEl = this.rootEl.createEl("div", {
      cls: "pca-status",
      text: "\uB300\uAE30 \uC911"
    });
  }
  createToolbarButton(parent, text, onClick) {
    const button = parent.createEl("button", { text });
    button.onclick = onClick;
  }
  async startLogin(button) {
    button.disabled = true;
    this.statusEl.setText("\uBE0C\uB77C\uC6B0\uC800 \uB85C\uADF8\uC778 \uC2DC\uC791 \uC911...");
    const code = await this.auth.login((message) => {
      if (message) {
        this.statusEl.setText(message);
      }
    });
    if (code === 0) {
      this.statusEl.setText("\uB85C\uADF8\uC778 \uC644\uB8CC. \uD654\uBA74\uC744 \uC804\uD658\uD569\uB2C8\uB2E4.");
      await this.render();
      return;
    }
    button.disabled = false;
    this.statusEl.setText("\uB85C\uADF8\uC778\uC774 \uC644\uB8CC\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4. \uBE0C\uB77C\uC6B0\uC800 \uCC3D\uC774 \uC5F4\uB838\uB294\uC9C0 \uD655\uC778\uD55C \uB4A4 \uC0C1\uD0DC\uB97C \uB2E4\uC2DC \uD655\uC778\uD558\uC138\uC694.");
  }
  async relogin() {
    this.codex.stop();
    this.addMessage("\uC2DC\uC2A4\uD15C", "\uC800\uC7A5\uB41C Codex \uB85C\uADF8\uC778 \uC815\uBCF4\uB97C \uC9C0\uC6B0\uACE0 \uB2E4\uC2DC \uB85C\uADF8\uC778\uD569\uB2C8\uB2E4.");
    this.statusEl.setText("Codex \uB85C\uADF8\uC544\uC6C3 \uC911...");
    await this.auth.logout((message) => {
      if (message) {
        this.statusEl.setText(message);
      }
    });
    this.rootEl.empty();
    this.renderSignedOut("\uAE30\uC874 \uB85C\uADF8\uC778 \uC815\uBCF4\uB97C \uC9C0\uC6E0\uC2B5\uB2C8\uB2E4. ChatGPT\uB85C \uB2E4\uC2DC \uB85C\uADF8\uC778\uD558\uC138\uC694.", true);
  }
  async sendWithContext(userInput, selectionOnly, dailyReview) {
    const trimmed = userInput.trim();
    if (!trimmed) {
      return;
    }
    this.inputEl.value = "";
    this.addMessage("\uB098", trimmed);
    this.statusEl.setText("\uBB38\uB9E5 \uC218\uC9D1 \uC911...");
    const prompt = await this.vaultContext.buildContextualPrompt(trimmed, selectionOnly, dailyReview);
    if (!prompt) {
      this.statusEl.setText("\uC5F4\uB824 \uC788\uB294 \uB178\uD2B8 \uC5C6\uC74C");
      return;
    }
    try {
      this.statusEl.setText("Codex\uC5D0 \uC804\uC1A1 \uC911...");
      this.codex.sendPrompt(prompt);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.addMessage("\uC2DC\uC2A4\uD15C", message);
      this.statusEl.setText("\uC804\uC1A1 \uC2E4\uD328");
    }
  }
  handleCodexEvent(event) {
    if (event.type === "message") {
      if (!this.shouldShowProtocolMessage(event.payload)) {
        return;
      }
      const text = this.extractText(event.payload);
      if (this.isUnauthorizedPayload(event.payload)) {
        this.addMessage("\uC2DC\uC2A4\uD15C", text);
        this.statusEl.setText("\uB2E4\uC2DC \uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4.");
        this.codex.stop();
        return;
      }
      this.lastAssistantText = text;
      this.addMessage("Codex", text);
      this.statusEl.setText("\uC751\uB2F5 \uC218\uC2E0");
      return;
    }
    if (event.type === "stderr") {
      const text = String(event.payload);
      if (/access token could not be refreshed|unauthorized|token_expired|authentication token is expired/i.test(text)) {
        this.addMessage("\uC2DC\uC2A4\uD15C", "Codex \uB85C\uADF8\uC778 \uD1A0\uD070\uC744 \uAC31\uC2E0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uC0C1\uB2E8\uC758 '\uB2E4\uC2DC \uB85C\uADF8\uC778'\uC744 \uB20C\uB7EC \uB2E4\uC2DC \uB85C\uADF8\uC778\uD558\uC138\uC694.");
        this.statusEl.setText("\uB2E4\uC2DC \uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4.");
        this.codex.stop();
        return;
      }
      this.addMessage("\uC2DC\uC2A4\uD15C", text);
      this.statusEl.setText("Codex \uB85C\uADF8 \uC218\uC2E0");
      return;
    }
    if (event.type === "error") {
      const error = event.payload instanceof Error ? event.payload.message : String(event.payload);
      this.addMessage("\uC2DC\uC2A4\uD15C", `Codex \uC2E4\uD589 \uC624\uB958: ${error}`);
      this.statusEl.setText("Codex \uC2E4\uD589 \uC2E4\uD328");
      return;
    }
    if (event.type === "exit") {
      this.addMessage("\uC2DC\uC2A4\uD15C", `Codex app-server \uC885\uB8CC: ${event.payload ?? "unknown"}`);
      this.statusEl.setText("Codex \uC885\uB8CC");
    }
  }
  extractText(payload) {
    if (this.isUnauthorizedPayload(payload)) {
      return "Codex \uB85C\uADF8\uC778 \uD1A0\uD070\uC744 \uAC31\uC2E0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uC0C1\uB2E8\uC758 '\uB2E4\uC2DC \uB85C\uADF8\uC778'\uC744 \uB20C\uB7EC \uB2E4\uC2DC \uB85C\uADF8\uC778\uD558\uC138\uC694.";
    }
    if (typeof payload === "string") {
      return payload;
    }
    if (payload && typeof payload === "object") {
      const record = payload;
      const notificationText = this.extractNotificationText(record);
      if (notificationText) {
        return notificationText;
      }
    }
    return JSON.stringify(payload, null, 2);
  }
  shouldShowProtocolMessage(payload) {
    if (this.isUnauthorizedPayload(payload)) {
      return true;
    }
    if (!payload || typeof payload !== "object") {
      return typeof payload === "string" && payload.trim().length > 0;
    }
    const record = payload;
    const method = record.method;
    if (typeof method !== "string") {
      return false;
    }
    if (method === "error" || method === "warning" || method === "guardianWarning") {
      return true;
    }
    if (method === "item/completed" || method === "rawResponseItem/completed") {
      return this.extractNotificationText(record) !== null;
    }
    if (method === "turn/completed") {
      return this.extractNotificationText(record) !== null;
    }
    return false;
  }
  extractNotificationText(record) {
    const method = record.method;
    const params = record.params;
    if (typeof method !== "string" || !params || typeof params !== "object") {
      return null;
    }
    const paramsRecord = params;
    if (method === "item/completed") {
      const item = paramsRecord.item;
      if (item && typeof item === "object") {
        const itemRecord = item;
        if (itemRecord.type === "agentMessage" && typeof itemRecord.text === "string") {
          return itemRecord.text;
        }
      }
    }
    if (method === "rawResponseItem/completed") {
      return this.extractRawResponseText(paramsRecord.item);
    }
    if (method === "turn/completed") {
      const turn = paramsRecord.turn;
      if (turn && typeof turn === "object") {
        const turnRecord = turn;
        if (turnRecord.status === "failed") {
          const error = turnRecord.error;
          if (error && typeof error === "object") {
            const message = error.message;
            return typeof message === "string" ? message : "Codex \uC694\uCCAD\uC774 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.";
          }
          return "Codex \uC694\uCCAD\uC774 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.";
        }
      }
      return null;
    }
    if ((method === "error" || method === "warning" || method === "guardianWarning") && typeof paramsRecord.message === "string") {
      return paramsRecord.message;
    }
    return null;
  }
  extractRawResponseText(item) {
    if (!item || typeof item !== "object") {
      return null;
    }
    const itemRecord = item;
    const content = itemRecord.content;
    if (!Array.isArray(content)) {
      return null;
    }
    const parts = content.map((part) => {
      if (!part || typeof part !== "object") {
        return "";
      }
      const partRecord = part;
      return partRecord.type === "output_text" && typeof partRecord.text === "string" ? partRecord.text : "";
    }).filter(Boolean);
    return parts.length > 0 ? parts.join("\n") : null;
  }
  isUnauthorizedPayload(payload) {
    if (!payload || typeof payload !== "object") {
      return false;
    }
    return /access token could not be refreshed|unauthorized|token_expired|authentication token is expired/i.test(JSON.stringify(payload));
  }
  addMessage(role, text) {
    const message = this.messagesEl.createDiv({ cls: `pca-message pca-message-${this.roleClass(role)}` });
    message.createEl("strong", { cls: "pca-role", text: role });
    message.createEl("div", { cls: "pca-message-body", text });
    this.messagesEl.scrollTo({ top: this.messagesEl.scrollHeight });
  }
  roleClass(role) {
    if (role === "\uB098") {
      return "user";
    }
    return role === "Codex" ? "assistant" : "system";
  }
  async saveDailyReview() {
    if (!this.lastAssistantText.trim()) {
      new import_obsidian2.Notice("\uC800\uC7A5\uD560 Codex \uB2F5\uBCC0\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const markdown = [
      `# Daily Review ${window.moment().format("YYYY-MM-DD")}`,
      "",
      this.lastAssistantText,
      ""
    ].join("\n");
    const path = await this.vaultContext.saveDailyReview(markdown);
    new import_obsidian2.Notice(`\uC800\uC7A5\uB428: ${path}`);
  }
};

// src/main.ts
var PersonalCodexAssistantPlugin = class extends import_obsidian3.Plugin {
  assistantSettings;
  codex;
  auth;
  vaultContext;
  approvals;
  async onload() {
    await this.loadSettings();
    this.codex = new CodexClient(this.assistantSettings);
    this.auth = new CodexAuth(this.assistantSettings.codexCommand);
    this.vaultContext = new VaultContext(this.app, this.assistantSettings);
    this.approvals = new ApprovalManager();
    this.registerView(
      ASSISTANT_VIEW_TYPE,
      (leaf) => new AssistantView(leaf, this.codex, this.auth, this.vaultContext, this.approvals)
    );
    this.addRibbonIcon("bot", "Codex Assistant \uC5F4\uAE30", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-personal-codex-assistant",
      name: "Open Personal Codex Assistant",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "create-assistant-files",
      name: "Create assistant context files",
      callback: async () => {
        await this.vaultContext.ensureAssistantFiles();
        new import_obsidian3.Notice("Assistant \uD3F4\uB354\uC640 \uAE30\uBCF8 \uBB38\uB9E5 \uD30C\uC77C\uC744 \uB9CC\uB4E4\uC5C8\uC2B5\uB2C8\uB2E4.");
      }
    });
    await this.vaultContext.ensureAssistantFiles();
  }
  onunload() {
    this.codex.stop();
    this.app.workspace.detachLeavesOfType(ASSISTANT_VIEW_TYPE);
  }
  async activateView() {
    const leaves = this.app.workspace.getLeavesOfType(ASSISTANT_VIEW_TYPE);
    let leaf = leaves[0] ?? null;
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: ASSISTANT_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.assistantSettings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.assistantSettings);
  }
};
